version: '3'
services:
  model-mlflow:
    build: ./deploy-mlflow
    #image: luntaixia/cnn-summarizer-mlflow
    ports:
      - 5003:5003
    restart: on-failure

  backend-mlflow:
    build: ./backend-fastapi
    #image: luntaixia/cnn-summarizer-backend
    ports:
      - 5000:5000
    environment:
      MODEL_URI: model-mlflow
    depends_on:
      - model-mlflow
    restart: on-failure

  backend-standalone:
    build: ./deploy-fastapi
    #image: luntaixia/cnn-summarizer-local
    ports:
      - 8000:8000
    restart: on-failure

  mysql:
    image: mysql:latest
    volumes:
      - /home/luntaixia/Downloads/mysql-storage:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=luntaixia
    ports:
      - 3306:3306
    command: ['mysqld', '--character-set-server=utf8mb4', '--default-authentication-plugin=mysql_native_password']

  monitoring:
    build: ./monitoring
    #image: luntaixia/cnn-summarizer-monitoring
    volumes:
      - ./secrets.toml:/app/.secrets/secrets.toml # for streamlit secrets
    ports:
      - 9020:9020
    depends_on:
      - mysql
    restart: on-failure

  grafana:
    image: grafana/grafana-oss
    container_name: grafana-server
    restart: always
    depends_on:
      - mysql
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      #- GF_INSTALL_PLUGINS=grafana-worldmap-panel  # world map plugin
    ports:
      - '3000:3000'
    volumes:
      - /home/luntaixia/Downloads/other-storage/grafana_data:/var/lib/grafana
    command: bash -c "docker login -u user -p password && /run.sh" # fix permission error using root user
    user: "root:root"

  frontend:
    build: ./frontend-streamlit
    #image: luntaixia/cnn-summarizer-frontend
    ports:
      - 8501:8501
    volumes:
      - ./secrets.toml:/app/.streamlit/secrets.toml # for streamlit secrets
    depends_on:
      - backend-mlflow
      - backend-standalone
      - monitoring
    restart: on-failure